spring:
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/jooq_test
    username: root
    hikari:
      auto-commit: true
      maximum-pool-size: 7
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/master.xml

